GET http://localhost:3000/api/users/currentuser

###
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
    "email": "tk7@gmail.com",
    "password": "1234"
}

### 
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/users/add-movies
Content-Type: application/json

{
    "userId": "6122a2e24aee3733608c9e0b",
    "movies": [
        {
            "genre": "test",
            "name": "test movie",
            "rating": "6.1",
            "popularity": "10",
            "release_year": "2020"
        },
        {
            "genre": "test 2",
            "name": "test movie 2",
            "rating": "6.1",
            "popularity": "10",
            "release_year": "2020"
        }
    ]
}

###
DELETE http://localhost:3000/api/users/delete-movies
Content-Type: application/json

{
    "userId": "6122a2e24aee3733608c9e0b",
    "movies": [
        {
            "name": "test movie"
        }
    ]
}

###
POST http://localhost:3000/api/users/get-movies
Content-Type: application/json

{
    "min": -1,
    "max": 10
}

###
GET https://8a08-103-59-205-109.ngrok.io/api/users/currentuser

###
POST https://8a08-103-59-205-109.ngrok.io/api/users/signin
Content-Type: application/json

{
    "email": "tkfds7@gmail.com",
    "password": "1234"
}

###
POST https://8a08-103-59-205-109.ngrok.io/api/users/signup
Content-Type: application/json

{
    "email": "tk7@gmail.com",
    "password": "1234"
}

###
GET https://recommender-backend.herokuapp.com/api/users/currentuser

###
POST https://recommender-backend.herokuapp.com/api/users/signup
Content-Type: application/json

{
    "email": "test@1234.com",
    "password": "1234"
}

###
POST https://recommender-backend.herokuapp.com/api/users/signin
Content-Type: application/json

{
    "email": "tk7@gmail.com",
    "password": "1234"
}

