GET http://localhost:3000/api/users/currentuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmUzOTEzZWQyOTg4MGE0OGEzNDBhZCIsImVtYWlsIjoidGVzdEB0ZXN0MTIzLmNvbSIsImlhdCI6MTYzMDQxOTM4MSwiZXhwIjoxNjMwNDIwMjgxfQ.brDZTD_Uknw7iQHxRIwnWx1ARR2pQvtt81pRM4MlEEY

###
GET http://localhost:3000/api/users/get-user-movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmUzOTEzZWQyOTg4MGE0OGEzNDBhZCIsImVtYWlsIjoidGVzdEB0ZXN0MTIzLmNvbSIsImlhdCI6MTYzMDQxOTM4MSwiZXhwIjoxNjMwNDIwMjgxfQ.brDZTD_Uknw7iQHxRIwnWx1ARR2pQvtt81pRM4MlEEY

###
GET http://localhost:3000/api/users/get-user-recommendations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmUzOTEzZWQyOTg4MGE0OGEzNDBhZCIsImVtYWlsIjoidGVzdEB0ZXN0MTIzLmNvbSIsImlhdCI6MTYzMDQxOTM4MSwiZXhwIjoxNjMwNDIwMjgxfQ.brDZTD_Uknw7iQHxRIwnWx1ARR2pQvtt81pRM4MlEEY

###
POST http://localhost:3000/api/users/search-movies
Content-Type: application/json

{
    "query": "squad"
}

###
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
     "email": "test@test123.com",
    "password": "1234"
}

### 
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "name": "Tanay K",
    "email": "test@test123.com",
    "password": "1234"
} 
###

###
POST http://localhost:3000/api/users/add-movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmUzOTEzZWQyOTg4MGE0OGEzNDBhZCIsImVtYWlsIjoidGVzdEB0ZXN0MTIzLmNvbSIsImlhdCI6MTYzMDQxOTM4MSwiZXhwIjoxNjMwNDIwMjgxfQ.brDZTD_Uknw7iQHxRIwnWx1ARR2pQvtt81pRM4MlEEY

{
    "userId": "612e3913ed29880a48a340ad",
    "movies": [
        {
            "genre": "test",
            "name": "test movie",
            "rating": "6.1",
            "popularity": "10",
            "release_year": "2020"
        },
        {
            "genre": "test 2",
            "name": "test movie 2",
            "rating": "6.1",
            "popularity": "10",
            "release_year": "2020"
        }
    ]
}

###
DELETE http://localhost:3000/api/users/delete-movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmEzYTU1ZTIzZTQ1MjRmODI4YWZjNSIsImVtYWlsIjoidGUyMjEzMzNAdGVzdC5jb20iLCJpYXQiOjE2MzAxNTkyMDUsImV4cCI6MTYzMDE2MDEwNX0.9W55jlfjlnmJUEczmsc7oZ_ApbmiywgXyb2DCmdg_Qk

{
    "userId": "612a3a55e23e4524f828afc5",
    "movies": [
        {
            "name": "test movie 2"
        }
    ]
}

###
POST http://localhost:3000/api/users/get-movies
Content-Type: application/json

{
    "min": 0,
    "max": 10
}

###
# GET https://8a08-103-59-205-109.ngrok.io/api/users/currentuser

# ###
# POST https://8a08-103-59-205-109.ngrok.io/api/users/signin
# Content-Type: application/json

# {
#     "email": "tkfds7@gmail.com",
#     "password": "1234"
# }

# ###
# POST https://8a08-103-59-205-109.ngrok.io/api/users/signup
# Content-Type: application/json

# {
#     "email": "tk7@gmail.com",
#     "password": "1234"
# }

# ###
# GET https://recommender-backend.herokuapp.com/api/users/currentuser

# ###
# POST https://recommender-backend.herokuapp.com/api/users/signup
# Content-Type: application/json

# {
#     "email": "test@1234.com",
#     "password": "1234"
# }

# ###
# POST https://recommender-backend.herokuapp.com/api/users/signin
# Content-Type: application/json

# {
#     "email": "tk7@gmail.com",
#     "password": "1234"
# }

